language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"
install:
  - pip install -e ".[dev]"
script:
  - meraki -h
  - meraki -v
  - coverage run -m pytest
  - codecov
